# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Giuseppe Crowind De Frenza
title: Programmer, Unity Developer
email: crowind.gdev@gmail.com
#website: crowind.github.io

# Dark Mode
darkmode: false

# Social links
twitter_username: _Crowind
github_username:  Crowind
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: crowind
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: CV
#  icon: fas fa-file-alt
#  url: https://github.com/Crowind/crowind.github.io/blob/master/downloads/Giuseppe-Crowind-De-Frenza_CV.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi! I'm Crowind and I live in Pisa, Italy.
 After getting my computer science degree i decided to focus on videogame development and I joined the TheSign Comics and Arts Academy, where I'm currently enrolled.

 My favourite fields are Shaders and Code Architecture.

 I have always been versatile. I have basic skills in 2D art, animation, design and game design! That's probably the reason I think the most important part of a project is a shared vision. 
 
 Tabletop games lover, outsite my house's walls I love to hike and I organize fighting games tournaments!

 For more info download my [CV here](https://github.com/Crowind/crowind.github.io/blob/master/downloads/Giuseppe-Crowind-De-Frenza_CV.pdf)!

content:
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Problem Solving&nbsp; <font size="5"> &#129370;&#129370;&#129370;&#129370;&#129370; </font>

      Global Vision&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font size="5"> &#129370;&#129370;&#129370;&#129370;&#129370; </font>

      Shaders&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font size="5">&#129370;&#129370;&#129370;&#129370;</font>

      English&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font size="5">&#129370;&#129370;&#129370;&#129370;&#129370;</font>

      Game Design&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font size="5">&#129370;&#129370;&#129370;</font>
      
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Beyond Machines
        sub_title: Programming, Design
        caption: Nov 2018 - Jul 2019
        link: https://gitlab.com/Crowind/lovepuzzlesandbox.git
        link_text: gitlab.com/Crowind/lovepuzzlesandbox.git
        #quote: >
        #  Programming, Design
        description: | # this will include new lines to allow paragraphs
         <img src="images/beyondMachines.png" height="250"/>
         
      - layout: left
        title: Re-Pair
        sub_title: Programming
        caption: Jan 2020
        link: https://globalgamejam.org/2020/games/re-pair-0-2
        link_text: https://globalgamejam.org/2020/games/re-pair-0-2
        #quote: >
        #  Programming, Design
        description: | # this will include new lines to allow paragraphs
         <img src="images/re-pair.png" height="250"/>

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
